(function() {var a=this&&this.Pa||function(){a=Object.assign||function(c){for(var b,d=1,e=arguments.length;d<e;d++){b=arguments[d];for(var f in b)Object.prototype.hasOwnProperty.call(b,f)&&(c[f]=b[f])}return c};return a.apply(this,arguments)};
if(!window.keyman.ui.name)try{var k=window.keyman,n=k.osk,p=k.util;if(p.isTouchDevice())throw"";k.ui={B:!1,c:null,Qa:null,u:null,v:null,Y:null,F:null,ja:null,i:null,S:null,s:null,m:[],l:null,X:[],C:[],j:"as",b:[],da:"un",ha:0,Fa:1,Da:null,w:null,G:"",Ba:0,Ca:0,languages:[],M:!1,H:0,R:""};var r=k.ui;r.name="toolbar";r.a={qa:"Languages",va:"Turn off KeymanWeb keyboards",ua:"Off",xa:"Show On Screen Keyboard",ta:"Select language"};r.a.SelectKeyboardPre="Select ";r.a.SelectKeyboardSuf="keyboard";r.a.AltKeyboardsPre=
"Alternate keyboards for ";r.a.AltKeyboardsSuf="";r.a.ca="Central America";r.a.sa="South America";r.a.na="Americas";r.a.eu="Europe";r.a.af="Africa";r.a.un="Undetermined";r.a.as="Asia";r.a.oc="Oceania";r.createNode=function(c,b,d,e){var f=document.createElement(c);b&&(f.id=b);d&&(f.className=d);e&&(f.innerHTML=e);if("a"==c||"area"==c||"map"==c)f.Ua=function(){return!1};return f};r.initialize=r.Sa=function(){if(k.initialized&&!r.B){var c=document.getElementById("KeymanWebControl");if(!c){if(null==document.body)return;
c=document.createElement("DIV");c.id="KeymanWebControl";document.body.insertBefore(c,document.body.firstChild);r.ya=c}c.style.visibility="hidden";c.style.maxHeight="35px";r.B=!0;if(!p.isTouchDevice()){p.linkStyleSheet(p.getOption("resources")+"ui/toolbar/kmwuitoolbar.css");r.g={};r.g.na={t:r.a.na,D:"0,3,0,37,24,32,35,37,43,47,49,52,65,54,68,57,71,56,73,59,75,60,93,61,93,57,103,49,118,41,126,41,136,23,148,17,156,14,164,5,164,0,57,0,35,5,25,9,5,8,49,52,65,54,68,57,71,56,73,59,75,60,93,61,94,58,97,58,101,59,107,60,114,64,115,68,114,77,104,74,98,75,96,78,95,82,90,81,85,80,82,76,78,74,74,73,65,68,57,61,82,82,95,82,96,78,98,75,104,74,114,77,120,79,124,83,126,87,141,90,142,97,138,103,135,113,127,116,123,124,115,131,112,132,109,138,117,139,140,141,141,146,134,148,114,145,109,148,100,148,91,143,91,130,96,111,89,102,83,95,77,89"};
r.g.eu={t:r.a.eu,D:"145,29,146,19,158,14,171,6,187,2,206,1,217,4,227,11,231,16,231,33,227,34,225,35,225,37,227,39,228,44,228,47,227,48,223,46,218,44,215,43,208,43,203,45,202,48,205,52,201,52,195,49,189,50,187,48,177,48,175,49,166,50,147,33"};r.g.af={t:r.a.af,D:"150,58,158,50,166,50,175,49,177,48,187,48,189,50,195,49,201,52,205,52,207,53,221,75,229,75,231,77,231,85,227,92,232,101,237,106,237,112,227,115,222,118,206,125,199,127,193,127,185,111,183,104,180,87,168,89,153,85,143,71,147,60"};r.g.as={t:r.a.as,
D:"219,1,221,6,228,12,231,16,231,33,227,34,225,35,225,37,227,39,229,45,232,48,239,48,240,49,239,53,242,60,243,65,249,70,252,81,259,87,271,87,278,95,289,100,303,101,311,98,320,98,323,98,323,84,311,81,308,73,307,65,317,57,330,50,334,44,348,36,364,38,375,34,375,8,355,8,336,5,292,1,285,0,219,0"};r.g.oc={t:r.a.oc,D:"288,117,289,107,303,101,311,98,323,98,323,84,333,77,344,73,362,80,369,88,375,96,375,141,352,143,323,142,316,136,310,130,291,130"};r.g.un={t:r.a.un,D:"205,52,202,48,203,45,208,43,215,43,218,44,223,46,227,48,232,48,239,48,240,49,239,53,242,60,243,65,237,76,231,77,229,75,221,75,207,53"};
r.c=r.createNode("div","kmw_controls");r.c.style.display="block";var b=r.createNode("a","kmw_controls_start",null," ");b.href="https://keyman.com/developer/keymanweb/";b.target="_blank";r.c.appendChild(b);r.v=r.createNode("div","kmw_btn_keyboards","kmw_button");r.v.title=r.a.ta;b=r.createNode("a",null,"kmw_button_a");b.href="#";b.onclick=r.Ma;b.appendChild(r.createNode("div","kmw_img_keyboards","kmw_img"));b.appendChild(r.createNode("div",null,"kmw_a",r.a.qa));b.appendChild(r.createNode("div",null,
"kmw_drop"));r.v.appendChild(b);r.s=r.createNode("div","kmw_selector");r.o=r.createNode("div","kmw_selector_regions");r.u=r.createNode("div","kmw_browsemap");b=r.createNode("img","kmw_region_browsemap");b.src=p.getOption("resources")+"ui/toolbar/blank.gif";b.useMap="#kmw_worldgrey16";r.u.appendChild(b);var d=r.createNode("map","kmw_worldgrey16");d.name="kmw_worldgrey16";for(var e in r.g)b=r.createNode("area"),b.shape="poly",b.alt="",b.href="#",b.title=r.g[e].t,b.Ra="true",b.onclick=function(f){return function(g){return r.Z(g,
f)}}(e),b.onmouseover=function(f){return function(g){return r.ga(g,f)}}(e),b.onmouseout=function(f){return function(g){return r.ma(g,f)}}(e),b.coords=r.g[e].D,d.appendChild(b);b=r.createNode("area");b.shape="default";b.Ta="true";b.alt="";b.onclick=r.h;d.appendChild(b);r.u.appendChild(d);r.o.appendChild(r.u);r.l={};b=r.createNode("ul");for(e in r.g)d=r.createNode("li"),r.l[e]=r.createNode("a",null,null,r.g[e].t),r.l[e].href="#",r.l[e].onclick=function(f){return function(g){return r.Z(g,f)}}(e),r.l[e].onmouseover=
function(f){return function(g){return r.ga(g,f)}}(e),r.l[e].onmouseout=function(f){return function(g){return r.ma(g,f)}}(e),d.appendChild(r.l[e]),b.appendChild(d);r.o.appendChild(b);r.s.appendChild(r.o);r.v.appendChild(r.s);r.c.appendChild(r.v);r.c.appendChild(r.ja=r.createNode("div","kmw_bar_off","kmw_bar"));r.F=r.createNode("div","kmw_btn_off","kmw_button_selected");b=r.createNode("a",null,"kmw_button_a");b.href="#";b.onclick=r.Ga;b.title=r.a.va;b.appendChild(r.createNode("div","kmw_img_off","kmw_img"));
b.appendChild(r.createNode("div",null,"kmw_a",r.a.ua));r.F.appendChild(b);r.c.appendChild(r.F);r.c.appendChild(r.Y=r.createNode("div","kmw_control_keyboards","kmw_button"));r.c.appendChild(r.S=r.createNode("div","kmw_bar_osk","kmw_bar"));r.i=r.createNode("div","kmw_btn_osk","kmw_button");b=r.createNode("a",null,"kmw_button_a");b.href="#";b.onclick=r.Na;b.title=r.a.xa;b.appendChild(r.createNode("div","kmw_img_osk","kmw_img"));r.i.appendChild(b);r.c.appendChild(r.i);r.c.appendChild(r.createNode("div",
"kmw_controls_end",null," "));e=r.createNode("div");e.id="kmw_map_preload";r.c.appendChild(e);r.c.appendChild(r.createNode("br",null,"kmw_clear"));c.appendChild(r.c);r.M=!0;r.H&&clearTimeout(r.H);r.H=setTimeout(r.N,0);p.attachDOMEvent(document.body,"click",r.fa,!1);r.j="eu";k.focusLastActiveElement()}}};r.Va=function(){var c=r.c;c&&c.parentNode.removeChild(c);(c=r.ya)&&c.parentNode.removeChild(c)};r.N=function(){if(r.M){r.M=!1;var c=0;r.m={};var b=k.getKeyboards();b.sort(r.Oa);for(c=r.o.childNodes.length;0<
c;c--)"kmw_selector_region"==r.o.childNodes[c-1].className&&r.o.removeChild(r.o.childNodes[c-1]);for(var d in r.g){r.m[d]=r.createNode("div",null,"kmw_selector_region");for(var e=r.createNode("div",null,"kmw_keyboard_col"),f=0,g=0,m="",l=0;l<b.length;l++){var h=b[l].RegionCode;if(!r.g[h]){if(d!=r.da)continue}else if(h!=d)continue;h=k.util.getLanguageCodes(b[l].LanguageCode);h[0]!=m&&(m=h[0],f++)}f=Number(((f+3)/4).toFixed(0));m="";for(l=0;l<b.length;l++){h=b[l].RegionCode;if(!r.g[h]){if(d!=r.da)continue}else if(h!=
d)continue;h=k.util.getLanguageCodes(b[l].LanguageCode);if(h[0]==m)h=r.languages[m].f,h.push?h.push(b[l]):r.languages[m].f=h.concat(b[l]);else{m=h[0];r.languages[m]={id:b[l].LanguageCode,name:b[l].LanguageName,f:[b[l]]};0==g%f&&0<g&&(r.m[d].appendChild(e),e=r.createNode("div",null,3==g/f?"kmw_keyboard_col_right":"kmw_keyboard_col"));g++;h=r.createNode("div",null,"kmw_language");var q=r.createNode("a",null,null,b[l].LanguageName);q.href="#";q.onclick=function(t){return function(x){return r.la(x,t)}}(r.languages[m]);
h.appendChild(q);e.appendChild(h);c++}}r.m[d].appendChild(e);r.m[d].appendChild(r.createNode("div",null,"kmw_clear"));r.o.appendChild(r.m[d])}r.Ea();r.Z(null,r.j);r.V();r.P&&r.ea(r.P);k.focusLastActiveElement()}};r.Oa=function(c,b){return c.RegionCode<b.RegionCode?-2:c.RegionCode>b.RegionCode?2:c.LanguageName<b.LanguageName?-1:c.LanguageName>b.LanguageName?1:0};r.I=function(c){for(var b=0;b<r.b.length;b++)if(r.b[b].lang.id==c.id)return b;return null};r.ba=function(c,b){var d=r.I(c);if(null==d){if(r.b.length>=
r.Fa){var e=2147483647;d=null;for(var f=0;f<r.b.length;f++)r.b[f].priority<e&&(d=f,e=r.b[f].priority);null!=d&&(e=r.b[d],r.C[e.lang.id]=null,r.X[e.lang.id]=null,r.Y.removeChild(e.O),r.b=0==d?r.b.slice(d+1):d==r.b.length-1?r.b.slice(0,d):r.b.slice(0,d).concat(r.b.slice(d+1)))}d=r.createNode("div",null,"kmw_button");e=r.createNode("a",null,"kmw_button_a"+(1<c.f.length?" kmw_norightgap":""));e.href="#";f=r.a.SelectKeyboardPre+b.Name;var g=r.a.SelectKeyboardSuf;0>f.toLowerCase().indexOf(g.toLowerCase())&&
(f=f+" "+g);e.title=f;e.onclick=function(h){return r.la(h,c)};e.appendChild(r.createNode("div","kmw_img_kbd","kmw_img"));r.R=r.truncate(c.name,28);e.appendChild(r.createNode("div",null,"kmw_a",r.R));d.appendChild(e);g=e;if(1<c.f.length){e=r.createNode("a",null,"kmw_button_a kmw_noleftgap");e.href="#";e.title=r.a.AltKeyboardsPre+c.name+r.a.AltKeyboardsSuf;e.onclick=function(h){return r.La(h,c)};var m=r.createNode("div",null,"kmw_a");f=r.truncate(b.Name.replace(/\s?keyboard/i,""),40-r.R.length);m.appendChild(r.X[c.id]=
r.createNode("span",null,"kmw_kbd",f));e.appendChild(m);e.appendChild(r.createNode("div",null,"kmw_drop"));d.appendChild(e);r.C[c.id]=r.createNode("ul",null,"kmw_selector_kbd");r.C[c.id].style.display="none";for(var l in c.f)m=r.createNode("li"),f=c.f[l].Name.replace(/\s?keyboard/i,""),f=f+" ["+c.f[l].ra+"]",e=r.createNode("a",null,null,f),e.href="#",e.title="",e.onclick=function(h,q){return function(t){return r.K(t,h,q,!0)}}(c,c.f[l]),m.appendChild(e),r.C[c.id].appendChild(m);d.appendChild(r.C[c.id])}r.Y.appendChild(d);
r.b.push({priority:r.ha++,lang:c,W:b,O:d,aa:g})}else{r.b[d].priority=r.ha++;r.b[d].W=b;if(l=r.X[c.id])f=b.Name.replace(/\s?keyboard/i,""),l.innerHTML=r.truncate(f,40-r.R.length);r.b[d].aa&&(f=r.a.SelectKeyboardPre+b.Name,g=r.a.SelectKeyboardSuf,0>f.toLowerCase().indexOf(g.toLowerCase())&&(f=f+" "+g),r.b[d].aa.title=f)}};r.truncate=function(c,b){return c.length<=b?c:c.substr(0,b-1)+"\u2026"};r.Ka=function(){r.M=!0;r.H&&clearTimeout(r.H);r.H=setTimeout(r.N,0)};k.addEventListener("keyboardregistered",
r.Ka);r.A=function(c){var b=r.ia;b&&(b.style.display="none");r.T();return r.h(c)};r.La=function(c,b){r.J(c);if(b=r.C[b.id]){if("block"==b.style.display)return r.A(c);b.style.display="block";r.ia=b;r.$(b,r.A)}return r.h(c)};r.la=function(c,b){var d=r.I(b);return(d=null==d?b.f[0]:r.b[d].W)?r.K(c,b,d,!0):!1};r.K=function(c,b,d,e){if(r.G){var f=r.I(r.G);null!=f&&(r.b[f].O.className="kmw_button")}r.F.className="kmw_button";r.G=b;r.w=d;r.wa=d.ra;r.L();r.ba(b,d);e&&k.setActiveKeyboard(d.InternalName,d.LanguageCode);
r.b[r.I(b)].O.className="kmw_button_selected";r.ka();r.V();return r.J(c)||r.A(c)};r.V=function(){var c=[r.F,r.ja,r.i,r.S],b=!1;k.isCJK(r.w)?b=!0:null==r.w&&(b="none"==c[2].style.display);if(null!=r.w||0<r.b.length)for(var d=0;d<c.length;d++)c[d].style.display="";else for(d=0;d<c.length;d++)c[d].style.display="none";b?r.i.style.display=r.S.style.display="none":null==r.w&&(r.i.className="kmw_button_disabled");r.c.parentNode.style.visibility="visible"};r.L=function(){k.focusLastActiveElement()};r.Na=
function(c){n&&""!=k.getActiveKeyboard()&&(n.isEnabled()?n.hide():n.show(!0));r.L();return r.h(c)};r.Ga=function(c){if("kmw_controls_disabled"!=r.c.className){r.A(null);if(r.G){var b=r.I(r.G);null!=b&&(r.b[b].O.className="kmw_button")}r.w=null;r.G=null;r.wa="";r.F.className="kmw_button_selected"}r.L();k.setActiveKeyboard("","");r.ka();r.V();return r.h(c)};r.h=function(c){c||(c=window.event);window.event&&(window.event.returnValue=!1);c&&(c.cancelBubble=!0);return!1};r.Z=function(c,b){var d=r.u;if(!d)return r.h(c);
d.className="kmw_browsemap_"+b;"undefined"==typeof r.m[b]&&(r.M=!0,r.N());r.m[b].style.display="block";r.l[b].className="selected";null!=r.j&&r.j!=b&&(r.m[r.j].style.display="none",r.l[r.j].className="");r.j=b;return r.h(c)};r.ma=function(c,b){r.u.className=null==r.j?"":"kmw_browsemap_"+r.j;r.l[b].className=r.j==b?"selected":"";return r.h(c)};r.ga=function(c,b){r.u.className="kmw_browsemap_"+b+"_sel";r.l[b].className="hover";return r.h(c)};r.Ja=function(c){return c.getAttribute?c.getAttribute("kmw_disable")||
c.kmw_disable:c.kmw_disable};r.Aa=function(c){if(!r.B)return!0;c=c.target;if("textarea"==c.tagName.toLowerCase()||"input"==c.tagName.toLowerCase()&&"text"==c.type.toLowerCase())if(r.Da=c,r.Ja(c))"kmw_controls_disabled"!=r.c.className&&(r.c.className="kmw_controls_disabled");else{null!=r.w&&(k.isCJK()?r.i.style.display=r.S.style.display="none":r.i.className=n&&n.isEnabled()?"kmw_button_selected":"kmw_button");""!=r.c.className&&(r.c.className="");var b=c.oa?c.oa:64;var d=c.pa?c.pa:0;r.Ba=p.getAbsoluteX(c)+
b;r.Ca=p.getAbsoluteY(c)+c.offsetHeight+d}return!0};k.addEventListener("controlfocused",r.Aa);r.za=function(){if(!r.B)return!0;"none"!=r.i.style.display&&(r.i.className="kmw_button_disabled");return!0};k.addEventListener("controlblurred",r.za);r.P=null;r.ea=function(c){r.P=null;var b=c.internalName,d=k.util.getLanguageCodes(c.languageCode)[0];if(""!=d&&""!=b){d=r.languages[d];if(null!=d)for(var e=0;e<d.f.length;e++)if(d.f[e].InternalName==b)return r.K(null,d,d.f[e],!1),!0;r.P=a({},c)}return!0};k.addEventListener("keyboardchange",
r.ea);r.Ia=function(c){r.B&&(r.i.className="kmw_button_selected");return c};n.addEventListener("show",r.Ia);r.Ha=function(c){r.B&&c.HiddenByUser&&(r.i.className="kmw_button")};n.addEventListener("hide",r.Ha);r.Ma=function(c){r.N();if("kmw_controls_disabled"==r.c.className)return r.h(c);r.A(null);if("kmw_over"==r.s.className)return r.J(c);r.s.className="kmw_over";r.v.className="kmw_button_selected";r.$(r.s,r.J);return r.h(c)};r.J=function(c){r.s.className="";r.v.className="kmw_button";r.T();return r.h(c)};
r.fa=function(c){var b=r.ia;if((!b||"none"==b.style.display)&&""==r.s.className)return!0;r.J(c);r.A(c);return r.h(c)};var u=null,v=null,w=null;r.U=function(c){var b=c&&c.target||window.event&&window.event.srcElement;if(b)for(;b.parentNode;){if(b==v)return null;b=b.parentNode}"#document"==b.nodeName&&r.fa(c);return u};r.$=function(c,b){r.U==document.onclick&&r.T();u=b;v=c;w=document.onclick;document.onclick=r.U};r.T=function(){r.U==document.onclick&&(document.onclick=w,v=u=w=null)};r.Ea=function(){var c=
"",b=p.loadCookie("KeymanWeb_Keyboard");void 0!=b.current&&(c=b.current.split(":")[0]);b=p.loadCookie("KeymanWeb_Toolbar");void 0!=b.region&&(r.j=b.region);if(void 0!=b.maxrecent)for(var d=0;d<b.maxrecent;d++){if(void 0!=b["recent"+d]){var e=b["recent"+d].split(",");if(2==e.length){var f=r.languages[e[0]];if(null!=f)for(var g=0;g<f.f.length;g++)if(f.f[g].InternalName==e[1]){r.ba(f,f.f[g]);if(f.f[g].InternalName==c){r.K(null,f,f.f[g],!0);window.focus();r.L();break}break}}}}else if(c=k.getActiveKeyboard(),
g=k.getActiveLanguage(),""!=g&&""!=c&&(b=r.languages[g],null!=b))for(g=0;g<b.f.length;g++)b.f[g].InternalName==c&&(r.K(null,b,b.f[g],!0),window.focus(),r.L())};r.ka=function(){var c={};c.region=r.j;c.maxrecent=""+r.b.length;for(var b=0;b<r.b.length;b++)c["recent"+b]=r.b[b].lang.id+","+r.b[b].W.InternalName;p.saveCookie("KeymanWeb_Toolbar",c)}}catch(c){};}());
//# sourceMappingURL=kmwuitoolbar.js.map
